import type { Metadata } from "next";
import "./globals.css";
import ResponsiveNav from "@/ui/nav/ResponsiveNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <main>{children}</main>
        <nav>
          <ResponsiveNav />
        </nav>
      </body>
    </html>
  );
}
